
import java.awt.Image;
import java.net.InetAddress;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tisha
 */
public class Share_screen extends javax.swing.JFrame {

    /**
     * Creates new form Share_screen
     */
    public Share_screen() {
        initComponents();
        setSize(800,820);
        setVisible(true);
          setLocationRelativeTo(null); 
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         ImageIcon ic=new ImageIcon("src/pics/blue.jpeg");
        Image img=ic.getImage().getScaledInstance(lb.getWidth(), lb.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ic1=new ImageIcon(img);
        lb.setIcon(ic1);
        ImageIcon ic2=new ImageIcon("src/pics/back_1.jpeg");
        Image img1=ic2.getImage().getScaledInstance(bb.getWidth(), bb.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ic3=new ImageIcon(img1);
        bb.setIcon(ic3);
       // setDefaultCloseOperation(PROPERTIES);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ip = new javax.swing.JLabel();
        bt = new javax.swing.JButton();
        bb = new javax.swing.JButton();
        lb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        ip.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        ip.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ip);
        ip.setBounds(70, 80, 640, 410);

        bt.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        bt.setText("GET IP");
        bt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btActionPerformed(evt);
            }
        });
        getContentPane().add(bt);
        bt.setBounds(280, 530, 250, 100);

        bb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbActionPerformed(evt);
            }
        });
        getContentPane().add(bb);
        bb.setBounds(20, 20, 110, 80);
        getContentPane().add(lb);
        lb.setBounds(0, 0, 810, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btActionPerformed
         try {
            // Get the local host address
            InetAddress localHost = InetAddress.getLocalHost();
            String ipAddress= localHost.getHostAddress();
            ip.setText(ipAddress);
            } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btActionPerformed

    private void bbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbActionPerformed
Welcome obj=new Welcome();
obj.setVisible(true);
dispose();
 
    }//GEN-LAST:event_bbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Share_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Share_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Share_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Share_screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Share_screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bb;
    private javax.swing.JButton bt;
    private javax.swing.JLabel ip;
    private javax.swing.JLabel lb;
    // End of variables declaration//GEN-END:variables
}
