
import java.awt.Image;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author tisha
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
        setSize(800,820);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ImageIcon ic=new ImageIcon("src/pics/blue.jpeg");
        Image img=ic.getImage().getScaledInstance(lb1.getWidth(), lb1.getHeight(),Image.SCALE_SMOOTH);
        ImageIcon ic1=new ImageIcon(img);
        lb1.setIcon(ic1);
        
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bt2 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));
        setForeground(new java.awt.Color(153, 255, 255));
        getContentPane().setLayout(null);

        bt2.setBackground(new java.awt.Color(0, 0, 0));
        bt2.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        bt2.setForeground(new java.awt.Color(255, 255, 255));
        bt2.setText("GET SCREEN");
        bt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(160, 570, 440, 120);

        bt1.setBackground(new java.awt.Color(0, 0, 0));
        bt1.setFont(new java.awt.Font("Segoe UI Black", 3, 24)); // NOI18N
        bt1.setForeground(new java.awt.Color(255, 255, 255));
        bt1.setText("SHARE SCREEN");
        bt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(160, 390, 440, 120);

        l2.setBackground(new java.awt.Color(51, 204, 255));
        l2.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        l2.setForeground(new java.awt.Color(0, 51, 51));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("To");
        l2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        l2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        l2.setOpaque(true);
        getContentPane().add(l2);
        l2.setBounds(330, 120, 80, 70);

        l3.setBackground(new java.awt.Color(51, 204, 255));
        l3.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        l3.setForeground(new java.awt.Color(0, 51, 51));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Team Viewer");
        l3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 102, 255)));
        l3.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        l3.setOpaque(true);
        getContentPane().add(l3);
        l3.setBounds(200, 210, 350, 100);

        l1.setBackground(new java.awt.Color(51, 204, 255));
        l1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 48)); // NOI18N
        l1.setForeground(new java.awt.Color(0, 51, 51));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Welcome");
        l1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        l1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        l1.setOpaque(true);
        getContentPane().add(l1);
        l1.setBounds(200, 10, 350, 100);
        getContentPane().add(lb1);
        lb1.setBounds(0, 0, 800, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
Share_screen obj;
obj=new Share_screen();
obj.setVisible(true);
dispose();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
Get_screen obj2;
obj2=new Get_screen();
obj2.setVisible(true);
dispose();
    }//GEN-LAST:event_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Welcome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel lb1;
    // End of variables declaration//GEN-END:variables
}
